### PR TITLE
configure load-balancing with spring-retry (fixes #110)

### LINKED ISSUE #110: OAuth2LoadBalancerClientAutoConfiguration does not support RetryLoadBalancerInterceptor
`OAuth2LoadBalancerClientAutoConfiguration` only supports `LoadBalancerInterceptor` not `RetryLoadBalancerInterceptor` which is used as a replacement if `RetryTemplate` is available.

The fix should probably look like this:

```!java
@Configuration
@ConditionalOnClass({ LoadBalancerInterceptor.class, OAuth2RestTemplate.class })
@AutoConfigureAfter(OAuth2AutoConfiguration.class)
public class OAuth2LoadBalancerClientAutoConfiguration {

	@Configuration
	@ConditionalOnBean(LoadBalancerInterceptor.class)
	@ConditionalOnProperty(value = "security.oauth2.resource.loadBalanced", matchIfMissing = false)
	protected static class UserInfoLoadBalancerConfig {
		@Bean
		public UserInfoRestTemplateCustomizer loadBalancedUserInfoRestTemplateCustomizer(final LoadBalancerInterceptor loadBalancerInterceptor) {
			return new UserInfoRestTemplateCustomizer() {
				@Override
				public void customize(final OAuth2RestTemplate restTemplate) {
					final List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>(restTemplate
							.getInterceptors());
					interceptors.add(loadBalancerInterceptor);
					restTemplate.setInterceptors(interceptors);
				}
			};
		}
	}

	@Configuration
	@ConditionalOnBean(RetryLoadBalancerInterceptor.class)
	@ConditionalOnProperty(value = "security.oauth2.resource.loadBalanced", matchIfMissing = false)
	protected static class UserInfoRetryLoadBalancerConfig {
		@Bean
		public UserInfoRestTemplateCustomizer retryLoadBalancedUserInfoRestTemplateCustomizer(final RetryLoadBalancerInterceptor loadBalancerInterceptor) {
			return new UserInfoRestTemplateCustomizer() {
				@Override
				public void customize(final OAuth2RestTemplate restTemplate) {
					final List<ClientHttpRequestInterceptor> interceptors = new ArrayList<>(restTemplate
							.getInterceptors());
					interceptors.add(loadBalancerInterceptor);
					restTemplate.setInterceptors(interceptors);
				}
			};
		}
	}

}
```

### PR DESCRIPTION
**Pull request by sfussenegger**

### CODE REVIEW

**Comment by sfussenegger** [comment]
The problem is that to activate this behavior it requires `@ConditionalOnClass(RetryTemplate.class)` in `org.springframework.cloud.client.loadbalancer.LoadBalancerAutoConfiguration` to be true. Adding `spring-retry` changes the other part of the configuration that fires with `@ConditionalOnMissingClass("org.springframework.retry.support.RetryTemplate")`. So if you have an idea how to mock `@ConditionalOnClass{Missing,}Class` please let me know.

However, it turns out that the tests in `OAuth2LoadBalancerClientAutoConfigurationTests` don't really test for any of that but for the presence of `loadBalancedOauth2RestTemplate` which used to be [there until 1.0.2](https://github.com/spring-cloud/spring-cloud-security/blob/1.0.2.RELEASE/spring-cloud-security/src/main/java/org/springframework/cloud/security/oauth2/client/OAuth2LoadBalancerClientAutoConfiguration.java) but [was removed](https://github.com/spring-cloud/spring-cloud-security/commit/0fbadd3a7300035cb3af25ab56a889086fcbb09c). I've now updated the tests to at least check the non-load-balanced user info

**Comment by ryanjbaxter** [comment]
@sfussenegger to simulate spring retry not being on the classpath try using `@ClassPathExclusions`.  See https://github.com/spring-cloud/spring-cloud-netflix/blob/384c9b9725dac5200f2ffb2b1e31270bc5afffff/spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/ribbon/okhttp/SpringRetryDisableOkHttpClientTests.java

**Comment by ryanjbaxter** [comment]
@sfussenegger think you might be able to get this PR updated soon?  We are looking at doing another Dalston release soon.

**Comment by sfussenegger** [comment]
@ryanjbaxter I've tried using `@RunWith(FilteredClassPathRunner.class)` with `@ClassPathExclusions` but once I add it the test fails with this exception:

```

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_121]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_121]
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.11.jar:8.5.11]
	... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.StandardRoot@133427bb]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:112) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:140) [tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4842) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4974) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.11.jar:8.5.11]
	... 6 common frames omitted
Caused by: java.lang.Error: factory already defined
	at java.net.URL.setURLStreamHandlerFactory(URL.java:1112) ~[na:1.8.0_121]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:683) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:666) ~[tomcat-embed-core-8.5.11.jar:8.5.11]
	at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107) [tomcat-embed-core-8.5.11.jar:8.5.11]
	... 10 common frames omitted
```

In a nutshell, Tomcat calls `java.net.URL.setURLStreamHandlerFactory(URLStreamHandlerFactory)` when starting. This method can only be called once per JVM. While the default JUnit runner does some voodoo to avoid this, `FilteredClassPathRunner` lacks this feature.

Thoughts?

**Comment by ryanjbaxter** [comment]
Sorry dont have any thoughts.  When I have used this it wasnt for integration tests so tomcat wasnt started.  I suppose what you have is good enough, unless someone else disagrees.

**Pull request merged**
